name: Run Regibox Script Daily

on:
  schedule:
    # Run at 10:31 on Wednesdays, config is UTC time
    - cron: '31 9 * * WED'
    # Run at 11:41 on Wednesdays
    - cron: '41 10 * * WED'
    # Run at 17:01 every day
    - cron: '1 16 * * *'
    # Run at 18:01 every day
    - cron: '1 17 * * *'
    # Run at 19:01 only on Saturdays
    - cron: '1 18 * * SAT'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Set up virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -ac &

      - name: Run the script
        run: |
          python script.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DISPLAY: ":99"
